language: cpp
dist: trusty
sudo: false
os: linux

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - boost1.67

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
  - mkdir tmp
  - cd tmp
  - cmake ..
  - make

script:
  - ./Vector/Vector -l test_suite
  - ./Simple_Heap/Simple_Heap -l test_suite
  - ./Heap/Heap -l test_suite
  - ./Binomial_Heap/Binomial_Heap -l test_suite
  - ./Fibonachi_Heap/Fibonachi_Heap -l test_suite
  - ./TestAll/TestAll -l test_suite
